version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 12345:12345
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DBNAME=mydatabase
      - MONGO_COLLECTION=mycollection

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 80:8080

volumes:
  mongodb_data:
